import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <div className="min-h-screen bg-gray-100 dark:bg-gray-900">
        <header className="w-full bg-white dark:bg-gray-800 shadow-md p-4">
          <div className="container mx-auto flex justify-between items-center">
            <h1 className="text-xl font-bold">ShareLink</h1>
          </div>
        </header>
        <main className="container mx-auto p-4">{children}</main>
      </div>
    </>
  );
}
